### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mslinn** [trbngr/dutchman-sample#1]
You asked for a code review. Looks great! However, `git clone` followed by `sbt run` ends with this:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: commons-logging#commons-logging;1.1.3: configuration not found in commons-logging#commons-logging;1.1.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.5.2 compile
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          commons-logging:commons-logging:1.1.3
[warn]            +- com.amazonaws:aws-java-sdk-core:1.11.66
[warn]            +- com.caliberweb:dutchman-aws_2.12:1.0.4 ((ammonite.AmmonitePlugin) AmmonitePlugin.scala#L72)
[warn]            +- default:dutchman-sample_2.12:1.0
sbt.ResolveException: unresolved dependency: commons-logging#commons-logging;1.1.3: configuration not found in commons-logging#commons-logging;1.1.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.5.2 compile
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: commons-logging#commons-logging;1.1.3: configuration not found in commons-logging#commons-logging;1.1.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.5.2 compile
[error] Total time: 19 s, completed Dec 31, 2016 4:24:51 PM
```

**Comment by trbngr** [comment]
Thanks man. I'm out of town currently. I'll be happy to help solve this next week.

**Comment by trbngr** [comment]
Unfortunately, I can't repro this. Can you try to `git pull origin master` to get latest and try again?

And make sure `sbt` is up to date?

**Comment by trbngr** [comment]
Seems to be [this](https://stackoverflow.com/a/28456949/458325).

**Comment by mslinn** [comment]
````
$ sbt sbt-version
[info] Loading global plugins from /home/mslinn/.sbt/0.13/plugins
[info] Loading project definition from /var/work/experiments/sbt/test/optionTest/project
[info] Set current project to change-me (in build file:/var/work/experiments/sbt/test/optionTest/)
[info] 0.13.13

$ mv ~/.ivy2{,-}

$ sbt run
[snip]
[info] Compiling 3 Scala sources to /var/work/experiments/scala/dutchman-sample/target/scala-2.12/classes...
[info] Running io.example.Example
13:43:41,644 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
13:43:41,644 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
13:43:41,645 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/var/work/experiments/scala/dutchman-sample/target/scala-2.12/classes/logback.xml]
13:43:41,688 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
13:43:41,690 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
13:43:41,710 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ch.qos] to WARN
13:43:41,710 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to WARN
13:43:41,711 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.typesafe] to WARN
13:43:41,711 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
13:43:41,711 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
13:43:41,711 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
13:43:41,712 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@29826a86 - Registering current configuration as safe fallback point
DEBUG dutchman.circe.package$ - payload: {
  "index" : {
    "_index" : "dutchman_sample_index",
    "_type" : "person",
    "_id" : "1"
  }
}
[snip]
DEBUG dutchman.circe.package$ - payload: {
  "id" : 100,
  "first" : "Tracey",
  "last" : "Pullman"
}
something's amiss: Tcp command [Connect(localhost:9200,None,List(),Some(10 seconds),true)] failed

````

**Comment by trbngr** [comment]
Whoops. I assumed a local elasticsearch server room be running. 😒

**Comment by mslinn** [comment]
I did not run one while working through the issue. Might be an idea to add a check for room availability, and issue an error message if not.

Thanks!

**Comment by trbngr** [comment]
Room was a mobile typo. Haha. I meant to say an elasticsearch server to be running. I can add an embedded server though. It's kind of silly to assume such a thing when embedded is an option.
